name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  create:

jobs:
  build-android:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    # Setup ssh key for some repositories
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.10.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    #- run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-android.zip
        path: build/app/outputs/apk/release/app-release.apk
    - uses: papeloto/action-zip@v1
      with:
        files: build/app/outputs/apk/release/app-release.apk
        dest: release-android.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: release-android.zip
  build-ios:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # This job will run on ubuntu virtual machine
    runs-on: macos-latest
    steps:
    # Setup ssh key for some repositories
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.10.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    #- run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build apk.
    - run: flutter build ipa --release
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-ios.zip
        path: build/ios/ipa/
    - uses: papeloto/action-zip@v1
      with:
        files: build/ios/ipa/
        dest: release-ios.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: release-ios.zip
  build-web:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    # Setup ssh key for some repositories
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.10.x' # you can also specify exact version of flutter

    # Adicionando código referente a remoção do comportamento padrão do clique com botão direito do mouse
    - run: perl -pi -e "s|//import 'dart:html';|import 'dart:html';|g" lib/View/GanttChart.dart
    - run: perl -pi -e "s|//document.onContextMenu.listen\(\(event\) => event.preventDefault\(\)\);|document.onContextMenu.listen\(\(event\) => event.preventDefault\(\)\);|g" lib/View/GanttChart.dart
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    #- run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build apk.
    - run: flutter build web
    
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-web.zip
        path: build/web/
    - uses: papeloto/action-zip@v1
      with:
        files: build/web/
        dest: release-web.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: release-web.zip
  build-windows:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # This job will run on ubuntu virtual machine
    runs-on: windows-latest
    steps:
    # Setup ssh key for some repositories
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.10.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    #- run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build apk.
    - run: flutter build windows
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-windows.zip
        path: build/windows/runner/Release/
    - uses: papeloto/action-zip@v1
      with:
        files: build/windows/runner/Release/
        dest: release-windows.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: release-windows.zip
  build-linux:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    # Setup ssh key for some repositories
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.10.x' # you can also specify exact version of flutter
    
    # Installing dependency libraries
    - run: sudo apt-get -y install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Check for any formatting issues in the code.
    #- run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    #- run: flutter analyze .
    
    # Run widget tests for our flutter project.
    #- run: flutter test
    
    # Build
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v2
      with:
        name: release-linux.zip
        path: build/linux/x64/release/bundle/
    - uses: papeloto/action-zip@v1
      with:
        files: build/linux/x64/release/bundle/
        dest: release-linux.zip
    - uses: softprops/action-gh-release@v1
      with:
        files: release-linux.zip
